language: c
sudo: required

services:
  - docker

env:
  - ver: 3.0.0-dev

script:
  - docker run -t -i --rm -v `pwd`:/bro-simple-scan  broplatform/bro:${ver}-dev zkg test /bro-simple-scan --version $(git rev-parse HEAD)
